accounts/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('accounts.views',
    url(r'^$', 'account_list'),
    url(r'^range/', 'account_range'),
    url(r'^add/', 'account_add'),
    url(r'^transfer/', 'account_transfer'),
    url(r'^view/(?P<account_id>\d*)/', 'account_view'),
    url(r'^void/', 'account_void'),
)

urls.py
from django.conf.urls.defaults import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'Accountant.views.home', name='home'),
    # url(r'^Accountant/', include('Accountant.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^login/', 'django.contrib.auth.views.login'),
    url(r'^logout/', 'django.contrib.auth.views.logout',
        kwargs={'next_page': '/accounts/'}),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^incomes/', include('incomes.urls')),
    url(r'^expenses/', include('expenses.urls')),
    url(r'^budget/', include('budget.urls')),
    url(r'^analytics/', include('analytics.urls')),
)

accounts/models.py
import decimal
import datetime

from django.contrib.auth.models import User
from django.db import models
from django.db import transaction
from django.db.models import Sum, Manager
from django.db.models.query import QuerySet
from django.db.models.signals import post_save


class Journal(models.Model):
    type = models.CharField(max_length=128)

    def __unicode__(self):
        return self.type


class Void(Journal):
    original = models.ForeignKey(Journal, related_name='+')


class Posting(models.Model):
    date = models.DateField(default=datetime.date.today)
    amount = models.DecimalField(max_digits=14, decimal_places=2,
	default=decimal.Decimal('0.00'))
    account = models.ForeignKey('Account')
    journal = models.ForeignKey(Journal)

    def __unicode__(self):
	return "%s, %.2f, %s" % (self.date, self.amount, self.account.name)


def posting_post_save(sender, instance, created, **kwargs):
    if created:
	account = instance.account
	amount = decimal.Decimal(instance.amount)
	account.balance += amount
	account.save()

post_save.connect(posting_post_save, sender=Posting)

# I used a custom QuerySet to allow filter chaining with get_running_balance,
# rather than attaching the method to Account.objects through AccountManager.
class AccountQuerySet(QuerySet):
    def get_running_balance(self, start_date, end_date):
        accounts = []

        for account in self:
            posting_list = Posting.objects.select_related().order_by(
		'date').filter(
                account=account).filter(
                date__gte=start_date).filter(
                date__lte=end_date)

            postings = []
	    day = datetime.timedelta(days=1)
	    bal_start = start_date - day
            running_balance = account.get_balance_on(bal_start)
            for posting in posting_list:
                name = Posting.objects.select_related().order_by(
		    'date').filter(
		    journal=posting.journal).exclude(
                    account=account)[0].account.name
                running_balance += posting.amount
                postings.append({
                    'date': posting.date.strftime("%B %d, %Y"),
                    'name': name,
                    'amount': posting.amount,
                    'balance': running_balance,
		    'journal': posting.journal.id,
                })

            accounts.append({
                'id': account.id,
                'name': account.name,
                'balance': account.balance,
                'postings': postings,
            })

        return accounts


class AccountManager(Manager):
    def get_query_set(self):
        return AccountQuerySet(self.model)

    def __getattr__(self, name):
	# This check stops a recursion depth problem described in Django
	# ticket #15062
	if name.startswith("_"):
	    raise AttributeError
	return getattr(self.get_query_set(), name)


class Account(models.Model):
    name = models.CharField(max_length=64)
    balance = models.DecimalField(max_digits=14, decimal_places=2,
	default=decimal.Decimal('0.00'))
    owner = models.ForeignKey(User)
    objects = AccountManager()

    def __unicode__(self):
	return "%s: %.2f" % (self.name, self.balance)

    def get_balance_on(self, date):
	postings = Posting.objects.order_by('date').filter(
	    account__id=self.id).filter(
	    date__lte=date)
	credits = postings.filter(amount__gt=0)
	debits = postings.filter(amount__lt=0)

	if credits.exists() or debits.exists():
	    credit_total = credits.aggregate(Sum('amount'))['amount__sum']
	    debit_total = debits.aggregate(Sum('amount'))['amount__sum']

	    if not credit_total:
		credit_total = decimal.Decimal('0.00')
	    if not debit_total:
		debit_total = decimal.Decimal('0.00')

	    total = credit_total + debit_total
	else:
	    total = decimal.Decimal('0.00')

	return total

    def add_credit(self, date, payer, amount):
        journal = Journal(type="Income")
        journal.save()

        credit_amt = amount.to_eng_string()
        debit_amt = '-' + credit_amt

        debit = Posting.objects.create(date=date, amount=debit_amt,
	    account=payer, journal=journal)
        credit = Posting.objects.create(date=date, amount=credit_amt,
	    account=self, journal=journal)

    def add_debit(self, date, payee, amount):
        journal = Journal(type="Expense")
        journal.save()

        credit_amt = amount.to_eng_string()
        debit_amt = '-' + credit_amt

        debit = Posting.objects.create(date=date, amount=debit_amt,
	    account=self, journal=journal)
        credit = Posting.objects.create(date=date, amount=credit_amt,
	    account=payee, journal=journal)

    def add_transfer(self, date, payee, amount):
	journal = Journal(type="Transfer")
	journal.save()

	credit_amt = amount.to_eng_string()
	debit_amt = '-' + credit_amt

	debit = Posting.objects.create(date=date, amount=debit_amt,
	    account=self, journal=journal)
	credit = Posting.objects.create(date=date, amount=credit_amt,
	    account=payee, journal=journal)

accounts/forms.py
import datetime

from django import forms
from django.contrib.auth.models import User
from accounts.models import Account, Journal, Void, Posting

class AccountAddForm(forms.ModelForm):
    name = forms.CharField(max_length=64, label='Account Name')
    class Meta:
        model = Account
        fields = ('name',)

    def process(self, uid):
        data = self.cleaned_data
        name = data['name']
        user = User.objects.get(id=uid)
        profile = user.get_profile()
        accounts = profile.accounts

        account = Account(name=name, owner=user)
        account.save()
        accounts.add(account)
        profile.save()
        user.save()


class AccountTransferForm(forms.Form):
    payer = forms.CharField(max_length=64)
    payee = forms.CharField(max_length=64)
    date = forms.DateField(('%m/%d/%Y',),
        widget=forms.DateTimeInput(format='%m/%d/%Y', attrs={
            'class': 'input',
            'size': '15',
        })
    )
    amount = forms.DecimalField(max_digits=14, decimal_places=2)

    def process(self, uid):
	user = User.objects.get(id=uid)
	profile = user.get_profile()
	accounts = profile.accounts
	data = self.cleaned_data

	payer = data['payer']
	payee = data['payee']
	amount = data['amount']

	payer = accounts.get_or_create(name=payer, owner=user)[0]
	payee = accounts.get_or_create(name=payee, owner=user)[0]
	payer.add_transfer(data['date'], payee, amount)


class TransactionForm(forms.Form):
    name = forms.CharField(max_length=64)
    amount = forms.DecimalField(max_digits=14, decimal_places=2)
    date = forms.DateField(('%m/%d/%Y',),
        widget=forms.DateTimeInput(format='%m/%d/%Y', attrs={
            'class': 'input',
            'size': '15',
        })
    )

    def clean(self):
        super(TransactionForm, self).clean()
        data = self.cleaned_data
        date = data['date']
        today = datetime.date.today()
        if date > today:
            raise forms.ValidationError("This date is in the future.")

        return data

    def process(self, uid, account_id):
        data = self.cleaned_data
        user = User.objects.get(id=uid)
        profile = user.get_profile()

        name = data['name']
        amount = data['amount']
        date = data['date']


class VoidForm(forms.Form):
    journal = forms.IntegerField(initial='')

    def process(self):
	data = self.cleaned_data
	journal_id = data['journal']
	journal = Journal.objects.get(id=journal_id)

	postings = Posting.objects.select_related().filter(journal=journal)
        credit = postings.get(amount__gt=0)
        debit = postings.get(amount__lt=0)

        today = datetime.date.today()
        amount = credit.amount
        void = Void.objects.create(original=journal)
        void_debit = Posting(date=today, account=credit.account,
	    amount=-amount, journal=void)
        void_credit = Posting(date=today, account=debit.account, amount=amount,
	    journal=void)
	void_debit.save()
	void_credit.save()
	

accounts/views.py
import decimal
import datetime
import json

from django.db import transaction
from django.db.models import Sum
from django.contrib.auth.decorators import login_required
from django.template import RequestContext
from django.shortcuts import render, redirect
from django.http import HttpResponse, Http404

from accounts.forms import AccountAddForm, AccountTransferForm, VoidForm
from accounts.models import Posting

@login_required
def account_list(request):
    profile = request.user.get_profile()
    start_date = profile.start_date
    end_date = profile.end_date
    accounts = profile.accounts.all().get_running_balance(start_date, end_date)

    c = RequestContext(request, {
	'accounts': accounts,
    })

    return render(request, 'accounts/account_list.html', context_instance=c)

@login_required
def account_range(request):
    start_year = int(request.GET.get('start_year'))
    start_month = int(request.GET.get('start_month'))
    start_day = int(request.GET.get('start_day'))
    end_year = int(request.GET.get('end_year'))
    end_month = int(request.GET.get('end_month'))
    end_day = int(request.GET.get('end_day'))

    start_date = datetime.date(start_year, start_month, start_day)
    end_date = datetime.date(end_year, end_month, end_day)
    profile = request.user.get_profile()
    accounts = profile.accounts.all().get_running_balance(start_date, end_date)

    c = RequestContext(request, {
	'accounts': accounts,
    })
    return render(request, "accounts/account_list.html", context_instance=c)
	    
@transaction.commit_on_success
@login_required
def account_add(request):
    user = request.user
    profile = user.get_profile()
    total = profile.get_total_balance()

    if request.method == 'POST':
	form = AccountAddForm(request.POST)
	if form.is_valid():
	    form.process(user.id)
	    return redirect('/accounts/')
    else:
	form = AccountAddForm()

    c = RequestContext(request, {
	'form': form,
    })

    return render(request, 'accounts/account_add.html', context_instance=c)

@transaction.commit_on_success
@login_required
def account_transfer(request):
    user = request.user
    profile = user.get_profile()
    total = profile.get_total_balance()

    if request.method == 'POST':
	form = AccountTransferForm(request.POST)
	if form.is_valid():
	    form.process(user.id)
	    return redirect('/accounts/')
    else:
	form = AccountTransferForm()

    c = RequestContext(request, {
	'form': form,
    })

    return render(request, 'accounts/account_transfer.html',
	context_instance=c)

@login_required
def account_view(request, account_id):
    user = request.user
    profile = user.get_profile()
    total = profile.get_total_balance()
    account_q = profile.accounts.get(id=account_id)

    account = {}
    account['id'] = account_q.id
    account['name'] = account_q.name
    account['balance'] = account_q.balance
    account['postings'] = []

    posting_q = Posting.objects.order_by('date').filter(
	account__id=account['id'])
    running_balance = decimal.Decimal('0.00')
    for posting in posting_q:
	date = posting.date
	journal_id = posting.journal.id
	name = Posting.objects.filter(journal__id=journal_id).exclude(
	    id=posting.id)[0].account.name
	amount = posting.amount
	running_balance += amount
	account['postings'].append({
	    'date': date,
	    'name': name,
	    'amount': amount,
	    'balance': running_balance,
	})

    c = RequestContext(request, {
	'account': account,
    })

    return render(request, 'accounts/account_view.html', context_instance=c)

@transaction.commit_on_success
@login_required
def account_void(request):
    if request.method == 'POST':
	form = VoidForm(request.POST)
	if form.is_valid():
	    form.process()
	    
    return redirect('/accounts/')

templates/accounts/account_add.html
{% extends "accounts/base.html" %}

{% block interface %}
    <form method="post" action="#">{% csrf_token %}
	{{ form.as_p }}
	<input type="submit" value="Add" />
    </form>
{% endblock %}

templates/accounts/account_list.html
{% extends "accounts/base.html" %}

{% block interface %}
    <div id="account-nav">
	<a id="add-account" href="/accounts/add/">+ Add Account</a>
	<a id="add-transfer" href="/accounts/transfer/">+ Add Transfer</a>
    </div>

    {% if accounts %}
    <div id="account-list">
        {% for account in accounts %}
        <div class="account">
	    <div class="account-summary">
		<span class="account-name">{{ account.name }}</span>
		<span class="balance">{{ account.balance|stringformat:".2f" }}
		    </span>
	    </div>
	    <form class="button-container" method="link"
		action="/incomes/add/{{ account.id }}">
		<input class="income-button" type="submit"
		    value="+ Add Income" />
	    </form>
	    <form class="button-container" method="link"
		action="/expenses/add/{{ account.id }}">
		<input class="expense-button" type="submit"
		    value="+ Add Expense" />
	    </form>

	    {% for posting in account.postings %}
	    <div class="posting">
		<form method="post" action="/accounts/void/">{% csrf_token %}
		    <input type="hidden" name="journal"
			value="{{ posting.journal }}" />
		    <input type="submit" value="Void" />
		</form>
		<span class="date">{{ posting.date }}</span>
		<span class="name">{{ posting.name }}</span>
		<span class="amount">{{ posting.amount|stringformat:".2f" }}
		    </span>
	    </div>
	    <div class="balance-result">Balance:
		<span class="amount">{{ posting.balance|stringformat:".2f" }}
		    </span>  
            </div>
	    {% endfor %}
	    <form method="link" action="/accounts/view/{{ account.id }}/">
		<input type="submit" value="View Details" />
	    </form>
        </div>
        {% endfor %}
    </div>
    {% else %}
        <a class="info" href="/accounts/add/">Create Your First Account</a>
    {% endif %}
{% endblock %}

templates/accounts/account_transfer.html
{% extends "accounts/base.html" %}

{% block interface %}
    <form action="#" method="post">{% csrf_token %}
	{{ form.as_p }}
	<input type="submit" value="Submit" />
    </form>
{% endblock %}

{% block footer %}
    {{ block.super }}

    <script type="text/javascript">
        $(function() {
            $("p #id_date").datepicker({ dateFormat: 'mm/dd/yy' });
        });
    </script>
{% endblock %}

templates/accounts/account_view.html
{% extends "accounts/base.html" %}

{% block interface %}
    <div class="account">
	<span class="account-name">{{ account.name }}</span>
	<span class="amount balance">{{ account.balance|stringformat:".2f" }}
	    </span>
	
	{% for posting in account.postings %}
	    <div class="posting">
		<span class="date">{{ posting.date }}</span>
		<span class="name">{{ posting.name }}</span>
		<span class="amount">{{ posting.amount|stringformat:".2f" }}
		    </span>
	    </div>
	    <div class="balance-result">
		<span class="balance-label">Balance:</span>
		<span class="amount">{{ posting.balance }}</span>
	    </div>
        {% endfor %}
    </div>
{% endblock %}

templates/accounts/base.html
<!DOCTYPE html>
<head>
{% block head %}
    <title>Djac</title>
    <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}base.css"/>
    <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}jquery-ui.css"/>
    <script type="text/javascript" src="{{ STATIC_URL }}jquery.min.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}jquery-ui.min.js"></script>
{% endblock %}
</head>

<body>
    <div id="navigation">
	<h1>DJAC</h1>
	<a class="navlink" href="/accounts">Accounts</a>
	<a class="navlink" href="/incomes">Incomes</a>
	<a class="navlink" href="/expenses">Expenses</a>
	<a class="navlink" href="/budget">Budget</a>
	<a class="navlink" href="/analytics/expenses/">Analytics</a>

	<div id="userinfo">
	    <div id="welcome">Welcome{% if user.isauthenticated %}
		, {{ user.first_name }}
	    {% endif %}!</div>
	    <div id="total">
		Balance: {{ total|stringformat:".2f" }}
	    </div>
	    <a id="logout" href="/logout/">Logout</a>
	</div>
    </div>

    <div id="interface">
	<div id="date-interface">
	    <div id="start-datepicker">
		<span class="datepicker-header">Start Date:</span>
	    </div>
	    <div id="end-datepicker">
		<span class="datepicker-header">End Date:</span>
	    </div>
	</div>
	{% block interface %}{% endblock %}
    </div>
</body>

{% block footer %}
<footer>
    <script type="text/javascript" src="{{ STATIC_URL }}daterange.js"></script>
    <script type="text/javascript">
	DateRange("{{ start_date }}", "{{ end_date }}");
    </script>
</footer>
{% endblock %}

</html>